/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Text,
  'female' : IDL.Null,
  'male' : IDL.Null,
  'nonBinary' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'createdAt' : Time,
  'goals' : IDL.Vec(IDL.Text),
  'gender' : Gender,
});
export const PhotoAnalysis = IDL.Record({
  'hairScore' : IDL.Nat,
  'overallScore' : IDL.Nat,
  'symmetryScore' : IDL.Nat,
  'timestamp' : Time,
  'skinScore' : IDL.Nat,
  'styleScore' : IDL.Nat,
  'photoId' : IDL.Text,
});
export const Message = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addPhotoAnalysis' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'addPhotoReference' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func(
      [IDL.Text, IDL.Nat, Gender, IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPhotoReference' : IDL.Func([IDL.Text], [ExternalBlob], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getUserAnalyses' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PhotoAnalysis)],
      ['query'],
    ),
  'getUserMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Nat, Gender, IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Text,
    'female' : IDL.Null,
    'male' : IDL.Null,
    'nonBinary' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'createdAt' : Time,
    'goals' : IDL.Vec(IDL.Text),
    'gender' : Gender,
  });
  const PhotoAnalysis = IDL.Record({
    'hairScore' : IDL.Nat,
    'overallScore' : IDL.Nat,
    'symmetryScore' : IDL.Nat,
    'timestamp' : Time,
    'skinScore' : IDL.Nat,
    'styleScore' : IDL.Nat,
    'photoId' : IDL.Text,
  });
  const Message = IDL.Record({
    'question' : IDL.Text,
    'answer' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addPhotoAnalysis' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'addPhotoReference' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func(
        [IDL.Text, IDL.Nat, Gender, IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPhotoReference' : IDL.Func([IDL.Text], [ExternalBlob], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getUserAnalyses' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PhotoAnalysis)],
        ['query'],
      ),
    'getUserMessages' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Nat, Gender, IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };