/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type Gender = { 'other' : string } |
  { 'female' : null } |
  { 'male' : null } |
  { 'nonBinary' : null };
export interface Message {
  'question' : string,
  'answer' : string,
  'timestamp' : Time,
}
export interface PhotoAnalysis {
  'hairScore' : bigint,
  'overallScore' : bigint,
  'symmetryScore' : bigint,
  'timestamp' : Time,
  'skinScore' : bigint,
  'styleScore' : bigint,
  'photoId' : string,
}
export type Time = bigint;
export interface UserProfile {
  'age' : bigint,
  'bio' : string,
  'username' : string,
  'createdAt' : Time,
  'goals' : Array<string>,
  'gender' : Gender,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMessage' : ActorMethod<[string, string], undefined>,
  'addPhotoAnalysis' : ActorMethod<
    [string, bigint, bigint, bigint, bigint, bigint],
    undefined
  >,
  'addPhotoReference' : ActorMethod<[string, ExternalBlob], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<
    [string, bigint, Gender, Array<string>, string],
    undefined
  >,
  'getAllProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPhotoReference' : ActorMethod<[string], ExternalBlob>,
  'getProfile' : ActorMethod<[Principal], UserProfile>,
  'getUserAnalyses' : ActorMethod<[Principal], Array<PhotoAnalysis>>,
  'getUserMessages' : ActorMethod<[Principal], Array<Message>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<
    [string, bigint, Gender, Array<string>, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];